BASE_DATA_DIR: ./data/submission_17327012_episodes/
TRAIN_HDF5_FILE: submission_17327012_train.hdf5
VAL_HDF5_FILE: submission_17327012_val.hdf5
TEAM_NAME: Stanley Zheng

MODEL_NAME: "imitation-cnn"
CHECKPOINT_PATH: ""

# Model Params
NUM_SHIP_ACTIONS: 7
NUM_SHIPYARD_ACTIONS: 3

# Training Params
IGNORE_EMPTY_SQUARES: true
